/**
 * External known-answer tests (KATs).
 *
 * Every expected value below was copied verbatim from its authoritative
 * published source (listed per section). None of these values were
 * generated by this implementation or any other library.
 *
 * RULE: if a KAT fails, fix the implementation. Never change an expected
 * value to match the implementation.
 */

/**
 * BIP39 — official Trezor vector set (english, passphrase "TREZOR"):
 * https://github.com/trezor/python-mnemonic/blob/master/vectors.json
 * Entries: [entropyHex, mnemonic, seedHex(with passphrase "TREZOR"), xprv]
 */
export const BIP39_TREZOR_VECTORS = [
  {
    entropyHex:
      '0000000000000000000000000000000000000000000000000000000000000000',
    mnemonic:
      'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art',
    seedHexTrezorPassphrase:
      'bda85446c68413707090a52022edd26a1c9462295029f2e60cd7c4f2bbd3097170af7a4d73245cafa9c3cca8d561a7c3de6f5d4a10be8ed2a5e608d68f92fcc8',
  },
  {
    entropyHex:
      '7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f',
    mnemonic:
      'legal winner thank year wave sausage worth useful legal winner thank year wave sausage worth useful legal winner thank year wave sausage worth title',
    seedHexTrezorPassphrase:
      'bc09fca1804f7e69da93c2f2028eb238c227f2e9dda30cd63699232578480a4021b146ad717fbb7e451ce9eb835f43620bf5c514db0f8add49f5d121449d3e87',
  },
  {
    entropyHex:
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
    mnemonic:
      'zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo vote',
    seedHexTrezorPassphrase:
      'dd48c104698c30cfe2b6142103248622fb7bb0ff692eebb00089b32d22484e1613912f0a5b694407be899ffd31ed3992c456cdf60f5d4564b8ba3f05a69890ad',
  },
] as const;

/**
 * BIP32 — specification Test vector 1:
 * https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
 */
export const BIP32_TEST_VECTOR_1 = {
  seedHex: '000102030405060708090a0b0c0d0e0f',
  master: {
    xpub: 'xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8',
    xprv: 'xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi',
  },
  m0h: {
    // Chain m/0_H
    xpub: 'xpub68Gmy5EdvgibQVfPdqkBBCHxA5htiqg55crXYuXoQRKfDBFA1WEjWgP6LHhwBZeNK1VTsfTFUHCdrfp1bgwQ9xv5ski8PX9rL2dZXvgGDnw',
    xprv: 'xprv9uHRZZhk6KAJC1avXpDAp4MDc3sQKNxDiPvvkX8Br5ngLNv1TxvUxt4cV1rGL5hj6KCesnDYUhd7oWgT11eZG7XnxHrnYeSvkzY7d2bhkJ7',
  },
  m0h1: {
    // Chain m/0_H/1
    xpub: 'xpub6ASuArnXKPbfEwhqN6e3mwBcDTgzisQN1wXN9BJcM47sSikHjJf3UFHKkNAWbWMiGj7Wf5uMash7SyYq527Hqck2AxYysAA7xmALppuCkwQ',
    xprv: 'xprv9wTYmMFdV23N2TdNG573QoEsfRrWKQgWeibmLntzniatZvR9BmLnvSxqu53Kw1UmYPxLgboyZQaXwTCg8MSY3H2EU4pWcQDnRnrVA1xe8fs',
  },
} as const;

/**
 * HKDF-SHA256 — RFC 5869, Appendix A, Test Cases 1 and 2:
 * https://www.rfc-editor.org/rfc/rfc5869
 */
export const RFC5869_CASE_1 = {
  ikmHex: '0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b',
  saltHex: '000102030405060708090a0b0c',
  infoHex: 'f0f1f2f3f4f5f6f7f8f9',
  length: 42,
  prkHex:
    '077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5',
  okmHex:
    '3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865',
} as const;

export const RFC5869_CASE_2 = {
  ikmHex:
    '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f',
  saltHex:
    '606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeaf',
  infoHex:
    'b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff',
  length: 82,
  prkHex:
    '06a6b88c5853361a06104c9ceb35b45cef760014904671014a193f40c15fc244',
  okmHex:
    'b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c59045a99cac7827271cb41c65e590e09da3275600c2f09b8367793a9aca3db71cc30c58179ec3e87c14c01d5c1f3434f1d87',
} as const;

/**
 * XChaCha20-Poly1305 — draft-irtf-cfrg-xchacha-03, Appendix A.3.1:
 * https://www.ietf.org/archive/id/draft-irtf-cfrg-xchacha-03.txt
 */
export const XCHACHA20_POLY1305_KAT = {
  plaintextHex:
    '4c616469657320616e642047656e746c656d656e206f662074686520636c6173' +
    '73206f66202739393a204966204920636f756c64206f6666657220796f75206f' +
    '6e6c79206f6e652074697020666f7220746865206675747572652c2073756e73' +
    '637265656e20776f756c642062652069742e',
  aadHex: '50515253c0c1c2c3c4c5c6c7',
  keyHex: '808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f',
  nonceHex: '404142434445464748494a4b4c4d4e4f5051525354555657',
  ciphertextHex:
    'bd6d179d3e83d43b9576579493c0e939572a1700252bfaccbed2902c21396cbb' +
    '731c7f1b0b4aa6440bf3a82f4eda7e39ae64c6708c54c216cb96b72e1213b452' +
    '2f8c9ba40db5d945b11b69b982c1bb9e3f3fac2bc369488f76b2383565d3fff9' +
    '21f9664c97637da9768812f615c68b13b52e',
  tagHex: 'c0875924c1c7987947deafd8780acf49',
} as const;
