/**
 * Protocol test-vector generator.
 * Run with: pnpm test -- --reporter=verbose generate-vectors
 *
 * Outputs a machine-readable JSON file at
 * protocol-test-vectors/cloakvault-vectors-v1.json
 * and a binary capsule file at
 * protocol-test-vectors/capsule.bin
 *
 * ALL values in the output are derived from the FIXED TEST MNEMONIC and the
 * DeterministicTestRNG(seed=1). This file contains TEST SECRETS ONLY and must
 * never be used with real funds.
 */
import { describe, it } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

import { FIXED_TEST_MNEMONIC, mnemonicToEntropy32 } from '../crypto/wallet';
import { masterFingerprintFromSeed, formatFingerprint } from '../crypto/fingerprint';
import { mnemonicToSeedSync } from '@scure/bip39';
import { DeterministicTestRNG } from '../crypto/rng';
import { generateVaultKey, encodeVaultKey } from '../crypto/vaultkey';
import {
  createCapsule,
  parseCapsule,
  CAPSULE_LENGTH,
} from '../crypto/capsule';
import { deriveCapsuleKey } from '../crypto/kdf';
import { bytesToHex } from '../crypto/bytes';
import { createShares } from '../crypto/shares';
import { rsEncode, legacyV1Parity30Pct } from '../rs/rs';

describe('Protocol test-vector generation', () => {
  it('writes protocol-test-vectors/cloakvault-vectors-v1.json', () => {
    const rng1 = DeterministicTestRNG.fromSeedNumber(1);

    // ── Wallet ──
    const entropy = mnemonicToEntropy32(FIXED_TEST_MNEMONIC);
    const bip39Seed = mnemonicToSeedSync(FIXED_TEST_MNEMONIC, '');
    const masterFp = masterFingerprintFromSeed(bip39Seed);

    // ── Vault Key ──
    const rngVk = DeterministicTestRNG.fromSeedNumber(1);
    const vaultKey = generateVaultKey(rngVk);
    const vaultKeyText = encodeVaultKey(vaultKey);

    // ── Capsule ──
    const rngCapsule = DeterministicTestRNG.fromSeedNumber(1);
    generateVaultKey(rngCapsule); // advance past vault key bytes
    const capsuleBytes = createCapsule(entropy, vaultKey, rngCapsule, 1);
    const capsuleFields = parseCapsule(capsuleBytes);

    // ── Derived capsule key ──
    const capsuleKey = deriveCapsuleKey(
      vaultKey,
      capsuleFields.capsuleId,
      capsuleFields.generation,
    );

    // ── Shares ──
    const rngShares = DeterministicTestRNG.fromSeedNumber(2);
    const { shareA, shareB } = createShares(vaultKey, rngShares, 1);

    // ── Reed-Solomon ──
    const sampleData = capsuleBytes; // 93 bytes
    const parity = legacyV1Parity30Pct(sampleData.length);
    const rsCodeword = rsEncode(sampleData, parity);

    // ── Output ──
    const vectors = {
      _WARNING: [
        'CLOAKVAULT PROTOCOL TEST VECTORS — FOR INTEROPERABILITY TESTING ONLY.',
        'These vectors contain TEST SECRETS derived from the all-zeros entropy mnemonic.',
        'Never use this mnemonic or Vault Key with real funds.',
        'All values derived from FIXED_TEST_MNEMONIC + DeterministicTestRNG(seed=1).',
      ],
      version: 'cloakvault-vectors-v1',
      generatedAt: new Date().toISOString().slice(0, 10),
      wallet: {
        mnemonic: FIXED_TEST_MNEMONIC,
        entropyHex: bytesToHex(entropy),
        bip39SeedHex_emptyPassphrase: bytesToHex(bip39Seed),
        masterFingerprintHex: bytesToHex(masterFp),
        masterFingerprintFormatted: formatFingerprint(masterFp),
      },
      vaultKey: {
        rawHex: bytesToHex(vaultKey),
        text: vaultKeyText,
        description: 'Generated by DeterministicTestRNG(seed=1), first 32 bytes',
      },
      capsule: {
        versionByte: capsuleFields.version,
        generation: capsuleFields.generation,
        capsuleIdHex: bytesToHex(capsuleFields.capsuleId),
        nonceHex: bytesToHex(capsuleFields.nonce),
        ciphertextHex: bytesToHex(capsuleFields.ciphertext),
        tagHex: bytesToHex(capsuleFields.tag),
        fullBinaryHex: bytesToHex(capsuleBytes),
        lengthBytes: CAPSULE_LENGTH,
        aadHex: bytesToHex(capsuleBytes.slice(0, 21)),
        derivedCapsuleKeyHex: bytesToHex(capsuleKey),
      },
      shares: {
        shareA,
        shareB,
        description: 'Generated by DeterministicTestRNG(seed=2); rejoin → same Vault Key',
      },
      reedSolomon: {
        description: `RS(${sampleData.length + parity},${sampleData.length}) over GF(2^8), parity=${parity}, primitive poly=0x11D`,
        inputDataHex: bytesToHex(sampleData),
        parityCount: parity,
        codewordHex: bytesToHex(rsCodeword),
        codewordLengthBytes: rsCodeword.length,
      },
    };

    const outDir = path.join(import.meta.dirname, '../../../../protocol-test-vectors');
    fs.mkdirSync(outDir, { recursive: true });

    const jsonPath = path.join(outDir, 'cloakvault-vectors-v1.json');
    fs.writeFileSync(jsonPath, JSON.stringify(vectors, null, 2) + '\n');

    const binPath = path.join(outDir, 'capsule.bin');
    fs.writeFileSync(binPath, capsuleBytes);

    const readmePath = path.join(outDir, 'README.md');
    fs.writeFileSync(readmePath, `# CloakVault Protocol Test Vectors

**⚠️ TEST SECRETS ONLY — FOR INTEROPERABILITY TESTING**

These vectors contain the **all-zeros-entropy mnemonic** (23× "abandon" + "art").
This is the CloakVault FIXED_TEST_MNEMONIC, a publicly known test seed.
Never use these values with real funds or on a live wallet.

## Files

| File | Description |
|------|-------------|
| \`cloakvault-vectors-v1.json\` | Complete protocol vectors (JSON) |
| \`capsule.bin\` | Raw 93-byte Recovery Capsule binary |

## How to use

An independent implementation should be able to:
1. Reproduce the wallet derivation (entropy → mnemonic → BIP39 seed → fingerprint).
2. Decode the Vault Key from its text representation (\`CVK1.\` prefix).
3. Derive the capsule key using HKDF-SHA256 (salt=capsuleId, info=CLOAKVAULT-V1-CAPSULE-KEY||generation).
4. Decrypt the capsule using XChaCha20-Poly1305 and recover the 32-byte entropy.
5. Verify RS encoding: RS-encode the capsule bytes and compare to the stored codeword.
6. Rejoin the two shares to recover the Vault Key.

## Construction

- Deterministic RNG: SHA-256(seed32 || uint64_be(counter)), seed = SHA-256("test:" || uint64_be(n)).
- All values from DeterministicTestRNG(seed=1) except shares (seed=2).
`);

    console.log(`\nProtocol test vectors written to: ${outDir}`);
    console.log(`  cloakvault-vectors-v1.json (${fs.statSync(jsonPath).size} bytes)`);
    console.log(`  capsule.bin (${fs.statSync(binPath).size} bytes)`);
    console.log(`  README.md`);
  });
});
