/**
 * Frozen v3 conformance-vector test: the checked-in vector is the EXPECTED
 * input; the implementation must reproduce every byte-determining field.
 * The vector is never regenerated by this suite — on mismatch, fix the
 * implementation, never the vector.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bytesToHex, hexToBytes } from '../crypto/bytes';
import { entropy32ToMnemonic, mnemonicToBip39Seed } from '../crypto/wallet';
import { masterFingerprintFromSeed, formatFingerprint } from '../crypto/fingerprint';
import { encodeVaultKey } from '../crypto/vaultkey';
import { deriveCapsuleKeyV2, createCapsuleV2, CAPSULE2_KEY_INFO } from '../crypto/capsule2';
import { rsEncode } from '../rs/rs';
import { encodePayload, RS_PARITY_BYTES, SENTINEL } from '../codec/footer';
import { renderFooter } from '../pipeline';

const VECTOR_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../../docs/cloakvault-v3-test-vector.json',
);

describe('frozen v3 spec-vector conformance (vector is the expected value)', () => {
  it('implementation reproduces every frozen byte-determining field', () => {
    const vector = JSON.parse(readFileSync(VECTOR_PATH, 'utf8'));

    const seedEntropy = hexToBytes(vector.inputs.seedEntropyHex);
    const vaultKey = hexToBytes(vector.inputs.vaultKeyHex);

    // entropy ↔ mnemonic
    const mnemonic = entropy32ToMnemonic(seedEntropy);
    expect(mnemonic).toBe(vector.inputs.mnemonic);

    // Vault Key textual encoding
    expect(encodeVaultKey(vaultKey)).toBe(vector.inputs.vaultKeyText);

    // HKDF
    expect(CAPSULE2_KEY_INFO).toBe(vector.hkdf.infoAscii);
    expect(bytesToHex(new TextEncoder().encode(CAPSULE2_KEY_INFO))).toBe(vector.hkdf.infoHex);
    expect(bytesToHex(deriveCapsuleKeyV2(vaultKey))).toBe(vector.hkdf.derivedCapsuleKeyHex);

    // 49-byte capsule, ciphertext, tag
    const capsule = createCapsuleV2(seedEntropy, vaultKey);
    expect(capsule.length).toBe(vector.capsule.lengthBytes);
    expect(bytesToHex(capsule)).toBe(vector.capsule.capsuleHex);
    expect(bytesToHex(capsule.slice(1, 33))).toBe(vector.capsule.ciphertextHex);
    expect(bytesToHex(capsule.slice(33))).toBe(vector.capsule.tagHex);

    // RS(83,49) codeword + 34 parity bytes
    expect(RS_PARITY_BYTES).toBe(vector.reedSolomon.parity);
    const codeword = rsEncode(capsule, RS_PARITY_BYTES);
    expect(codeword.length).toBe(vector.reedSolomon.n);
    expect(bytesToHex(codeword)).toBe(vector.reedSolomon.codewordHex);
    expect(bytesToHex(codeword.slice(49))).toBe(vector.reedSolomon.parityHex);

    // Bech32 token
    expect(SENTINEL).toBe(vector.bech32.sentinel);
    const token = encodePayload(capsule);
    expect(token.length).toBe(vector.bech32.tokenLength);
    expect(token).toBe(vector.bech32.token);

    // Deterministic rendering values contained in the vector
    const dateMatch = (vector.rendering.footerLines as string[])
      .join('\n')
      .match(/Printed (\d{2}\/\d{2}\/\d{4})/);
    expect(dateMatch).not.toBeNull();
    const footer = renderFooter(token, dateMatch![1]);
    expect(footer.lines).toEqual(vector.rendering.footerLines);

    // Fingerprint
    const fingerprint = formatFingerprint(masterFingerprintFromSeed(mnemonicToBip39Seed(mnemonic)));
    expect(fingerprint).toBe(vector.expectedRecovery.fingerprint);
    expect(mnemonic).toBe(vector.expectedRecovery.mnemonic);
  });
});
